image: docker:latest
services:
  - docker:dind

stages:
  - heroku_push

docker-build:
  stage: heroku_push
  before_script:
    - apk add git
  script:
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git HEAD:master

  only:
    refs:
      - tags
      - master
